import { app } from 'electron'
import { readFile } from 'fs/promises'
import { join } from 'path'

// Aszurex partnership mark, embedded as a base64 data URI into print/export
// HTML document footers (Phase 39) — read once and cached, same one-function
// shape as print.service.ts's jsBarcodeScriptCache.
//
// Deliberately NOT using print.service.ts's logoToFileUrl() (file:// URL)
// pattern here, even though both solve "embed an image in generated print
// HTML": that pattern exists for the business's own uploaded logo, an
// arbitrary user file living outside the app bundle, where a path reference
// is the only option. The Aszurex mark is a static bundled asset — base64
// keeps the generated HTML self-contained, which matters for the export
// flows (download-as-HTML/PDF) where the output may be viewed or converted
// outside the context that has resources/ on a resolvable path.
let aszurexMarkDataUriCache: string | null = null

async function getAszurexMarkDataUri(): Promise<string> {
  if (aszurexMarkDataUriCache !== null) return aszurexMarkDataUriCache

  const isDev = !app.isPackaged
  const p = isDev
    ? join(__dirname, '../../resources/aszurex-mark.png')
    : join(process.resourcesPath, 'aszurex-mark.png')
  try {
    const dataUri = `data:image/png;base64,${(await readFile(p)).toString('base64')}`
    aszurexMarkDataUriCache = dataUri // only a SUCCESSFUL read is cached — a transient failure (e.g. AV
    return dataUri                    // briefly locking the file right after install) must retry on the
  } catch {                           // next call, not permanently omit the mark for the rest of the session
    return ''
  }
}

function markImgTag(dataUri: string, fontSizePx: number): string {
  return dataUri
    ? `<img src="${dataUri}" alt="" style="height:${fontSizePx + 4}px;width:auto;vertical-align:middle;margin:0 2px" />`
    : ''
}

/** "Aszurex [mark] | www.aszurex.com" — the reusable brand suffix, for callers
 * (like the KOT ticket) that need their own lead-in text instead of the
 * standard "Generated by..." prefix. */
export async function aszurexBrandSuffixHtml(fontSizePx = 8): Promise<string> {
  const mark = markImgTag(await getAszurexMarkDataUri(), fontSizePx)
  return `Aszurex${mark} | www.aszurex.com`
}

/**
 * The standard "Generated by Sarang Business OS Lite | Aszurex [mark] | www.aszurex.com"
 * footer line used across every printed/exported document — including the
 * Aszurex partnership mark immediately to the right of "Aszurex", per the
 * founder's branding rule (Phase 39). Returns an HTML fragment (inline elements
 * only) suitable for dropping into an existing <p>/<div> footer container.
 */
export async function aszurexFooterHtml(fontSizePx = 8): Promise<string> {
  return `Generated by Sarang Business OS Lite | ${await aszurexBrandSuffixHtml(fontSizePx)}`
}
