import { app, BrowserWindow, dialog } from 'electron'
import * as XLSX from 'xlsx'
import { writeFile, unlink } from 'fs/promises'
import { join } from 'path'
import { getPrisma } from '../database/db'
import { aszurexFooterHtml } from '../utils/branding'
import { renderBarChart, renderStackedBarChart, renderLineChart, renderPieChart, CHART_STYLES } from '../utils/svg-charts'

export type ReportChartSpec =
  | { type: 'bar'; title: string; orientation?: 'horizontal' | 'vertical'; data: { label: string; value: number; color?: string }[]; valueIsCurrency?: boolean }
  | { type: 'stackedBar'; title: string; data: { label: string; segments: { value: number; color: string; name?: string }[] }[]; legend?: { name: string; color: string }[] }
  | { type: 'line'; title: string; data: { label: string; value: number }[]; valueIsCurrency?: boolean }
  | { type: 'pie'; title: string; data: { label: string; value: number; color?: string }[]; valueIsCurrency?: boolean }
// db is accessed via getPrisma() inside generateReportHtml

// BUG FOUND 2026-07-22: generateReportHtml interpolated every field — table
// cells, headers, title, business name/address — directly into the HTML
// string with no escaping at all, unlike print.service.ts's identically-
// purposed escHtml(), applied consistently on every field there. A
// customer/product/business name containing `<`, `>`, or `"` (real,
// user-enterable data — Customers/Products screens don't restrict these
// characters) could corrupt this exported report's HTML/table structure.
// Mirrors print.service.ts's escHtml exactly; kept as a small local
// duplicate rather than a cross-module export for a 4-line pure function.
function escHtml(s: string | number | null | undefined): string {
  if (s == null) return ''
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
}

// Plain-text form — used for CSV rows and Excel cells (line 40/78 below), where
// an embedded image isn't possible. The HTML report footer (line ~204) uses
// aszurexFooterHtml() instead, which adds the partnership mark inline.
const ASZUREX_FOOTER = 'Generated by Sarang Business OS Lite | Aszurex | www.aszurex.com'

// ─────────────────────────────────────────────────────────────────────────────
// CSV Export — UTF-8 with BOM so Excel opens correctly (RULE EXP002)
// ─────────────────────────────────────────────────────────────────────────────

export async function exportToCsv(params: {
  filename: string
  headers: string[]
  rows: (string | number | null | undefined)[][]
}): Promise<void> {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save CSV Report',
    defaultPath: params.filename,
    filters: [{ name: 'CSV Files', extensions: ['csv'] }]
  })
  if (!filePath) return

  const escape = (v: string | number | null | undefined): string => {
    if (v == null) return ''
    const s = String(v)
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`
    }
    return s
  }

  const lines = [
    params.headers.map(escape).join(','),
    ...params.rows.map(row => row.map(escape).join(','))
  ]
  lines.push('')
  lines.push(`"${ASZUREX_FOOTER}"`)

  // UTF-8 BOM
  const bom = '﻿'
  await writeFile(filePath, bom + lines.join('\r\n'), 'utf8')
}

// ─────────────────────────────────────────────────────────────────────────────
// Excel Export — SheetJS (xlsx)
// ─────────────────────────────────────────────────────────────────────────────

export async function exportToExcel(params: {
  filename: string
  sheets: { name: string; headers: string[]; rows: (string | number | null | undefined)[][] }[]
}): Promise<void> {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save Excel Report',
    defaultPath: params.filename,
    filters: [{ name: 'Excel Files', extensions: ['xlsx'] }]
  })
  if (!filePath) return

  const wb = XLSX.utils.book_new()

  for (const sheet of params.sheets) {
    const data = [sheet.headers, ...sheet.rows]
    const ws = XLSX.utils.aoa_to_sheet(data)

    // Style header row bold width hints
    const colCount = sheet.headers.length
    ws['!cols'] = Array.from({ length: colCount }, () => ({ wch: 20 }))
    ws['!rows'] = [{ hpt: 18 }]

    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31))
  }

  // Aszurex branding sheet
  const brandWs = XLSX.utils.aoa_to_sheet([
    [ASZUREX_FOOTER],
    [`Report generated: ${new Date().toLocaleString(undefined)}`]
  ])
  XLSX.utils.book_append_sheet(wb, brandWs, 'About')

  const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })
  await writeFile(filePath, buf)
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF Export — Electron printToPDF via hidden BrowserWindow
// ─────────────────────────────────────────────────────────────────────────────

export async function exportToPdf(params: { html: string; filename: string }): Promise<void> {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save PDF Report',
    defaultPath: params.filename,
    filters: [{ name: 'PDF Files', extensions: ['pdf'] }]
  })
  if (!filePath) return

  const tmpPath = join(app.getPath('temp'), `sarang-report-${Date.now()}.html`)
  await writeFile(tmpPath, params.html, 'utf8')

  const win = new BrowserWindow({
    show: false,
    webPreferences: { contextIsolation: true, sandbox: true, nodeIntegration: false }
  })

  try {
    await win.loadURL(`file://${tmpPath.replace(/\\/g, '/')}`)
    const pdfBuf = await win.webContents.printToPDF({
      printBackground: true,
      pageSize: 'A4',
      margins: { top: 0.4, bottom: 0.4, left: 0.4, right: 0.4 }
    })
    await writeFile(filePath, pdfBuf)
  } finally {
    win.destroy()
    unlink(tmpPath).catch(() => {})
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Report HTML generator — used by PDF export
// ─────────────────────────────────────────────────────────────────────────────

export async function generateReportHtml(params: {
  title: string
  subtitle?: string
  dateRange?: string
  summaryCards?: { label: string; value: string }[]
  charts?: ReportChartSpec[]
  tables: { heading?: string; headers: string[]; rows: (string | number | null)[][] }[]
  currencySymbol?: string
}): Promise<string> {
  const db = getPrisma()
  const bizProfile = await db.businessProfile.findFirst()
  const bizName = bizProfile?.businessName ?? 'Business'
  const bizAddr = bizProfile?.address ?? ''
  const taxNo = bizProfile?.taxNumber ?? ''
  const currencySym = params.currencySymbol ?? bizProfile?.currencySymbol ?? '₹'
  const generatedAt = new Date().toLocaleString(undefined, { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })

  const fmtPlain = (n: number) => n.toLocaleString(undefined, { maximumFractionDigits: 2 })
  const fmtCurrency = (n: number) => `${currencySym}${fmtPlain(n)}`

  const chartsHtml = (params.charts ?? []).map(spec => {
    if (spec.type === 'bar') {
      return renderBarChart({ title: spec.title, data: spec.data, orientation: spec.orientation, valueFormatter: spec.valueIsCurrency ? fmtCurrency : fmtPlain })
    }
    if (spec.type === 'stackedBar') {
      return renderStackedBarChart({ title: spec.title, data: spec.data, legend: spec.legend })
    }
    if (spec.type === 'line') {
      return renderLineChart({ title: spec.title, data: spec.data, valueFormatter: spec.valueIsCurrency ? fmtCurrency : fmtPlain })
    }
    return renderPieChart({ title: spec.title, data: spec.data, valueFormatter: spec.valueIsCurrency ? fmtCurrency : fmtPlain })
  }).join('')
  const chartsWrapperHtml = chartsHtml ? `<div class="charts-grid">${chartsHtml}</div>` : ''

  const summaryHtml = params.summaryCards?.length ? `
    <div class="summary-grid">
      ${params.summaryCards.map(c => `
        <div class="summary-card">
          <div class="summary-label">${escHtml(c.label)}</div>
          <div class="summary-value">${escHtml(c.value)}</div>
        </div>`).join('')}
    </div>` : ''

  const tablesHtml = params.tables.map(t => `
    ${t.heading ? `<h3 class="table-heading">${escHtml(t.heading)}</h3>` : ''}
    <table>
      <thead>
        <tr>${t.headers.map(h => `<th>${escHtml(h)}</th>`).join('')}</tr>
      </thead>
      <tbody>
        ${t.rows.map(row => `<tr>${row.map(cell => `<td>${cell == null ? '—' : escHtml(cell)}</td>`).join('')}</tr>`).join('')}
        ${t.rows.length === 0 ? `<tr><td colspan="${t.headers.length}" class="empty">No data</td></tr>` : ''}
      </tbody>
    </table>`).join('<div style="margin-top:24px"></div>')

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/>
<title>${escHtml(params.title)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11px; color: #1e293b; padding: 32px; background: #fff; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #00AEEF; }
  .biz-name { font-size: 18px; font-weight: 700; color: #00AEEF; }
  .biz-info { font-size: 10px; color: #64748b; margin-top: 4px; }
  .report-meta { text-align: right; }
  .report-title { font-size: 16px; font-weight: 700; color: #0f172a; }
  .report-subtitle { font-size: 10px; color: #64748b; margin-top: 4px; }
  .report-date { font-size: 9px; color: #94a3b8; margin-top: 2px; }
  .summary-grid { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 20px; }
  .summary-card { flex: 1; min-width: 140px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; }
  .summary-label { font-size: 9px; font-weight: 600; text-transform: uppercase; color: #64748b; margin-bottom: 4px; }
  .summary-value { font-size: 16px; font-weight: 700; color: #0f172a; }
  .table-heading { font-size: 12px; font-weight: 600; color: #0f172a; margin: 16px 0 8px; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  thead tr { background: #00AEEF; }
  thead th { color: #fff; font-size: 9px; font-weight: 700; text-transform: uppercase; padding: 7px 8px; text-align: left; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  tbody tr:hover { background: #eff6ff; }
  td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
  .empty { color: #94a3b8; font-style: italic; text-align: center; padding: 20px; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 9px; color: #94a3b8; }
  .footer strong { color: #00AEEF; }
  .charts-grid { display: flex; flex-wrap: wrap; gap: 20px; margin-bottom: 20px; }
  .charts-grid .chart-block { flex: 1; min-width: 320px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px; }
  ${CHART_STYLES}
  @media print { body { padding: 0; } }
</style></head><body>
<div class="header">
  <div>
    <div class="biz-name">${escHtml(bizName)}</div>
    <div class="biz-info">${escHtml(bizAddr)}${taxNo ? ` | Tax: ${escHtml(taxNo)}` : ''}</div>
  </div>
  <div class="report-meta">
    <div class="report-title">${escHtml(params.title)}</div>
    ${params.subtitle ? `<div class="report-subtitle">${escHtml(params.subtitle)}</div>` : ''}
    ${params.dateRange ? `<div class="report-subtitle">${escHtml(params.dateRange)}</div>` : ''}
    <div class="report-date">Generated: ${escHtml(generatedAt)}</div>
  </div>
</div>
${summaryHtml}
${chartsWrapperHtml}
${tablesHtml}
<div class="footer">${await aszurexFooterHtml(9)} | Currency: ${escHtml(currencySym)}</div>
</body></html>`
}
