// Central registry of all audit event action strings used across services
// Use these constants instead of inline string literals to prevent typos and enable search

export const AUDIT_EVENTS = {
  // Auth
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  TOKEN_AUTO_LOGIN: 'TOKEN_AUTO_LOGIN',

  // User management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  ROLE_PERMISSIONS_UPDATED: 'ROLE_PERMISSIONS_UPDATED',

  // Business & settings
  BUSINESS_PROFILE_UPDATED: 'BUSINESS_PROFILE_UPDATED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  INDUSTRY_TEMPLATE_CHANGED: 'INDUSTRY_TEMPLATE_CHANGED',

  // Products & categories
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',

  // Inventory
  STOCK_ADDED: 'STOCK_ADDED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',

  // Customers & suppliers
  CUSTOMER_CREATED: 'CUSTOMER_CREATED',
  CUSTOMER_UPDATED: 'CUSTOMER_UPDATED',
  CUSTOMER_ARCHIVED: 'CUSTOMER_ARCHIVED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_ARCHIVED: 'SUPPLIER_ARCHIVED',
  SUPPLIER_PAYMENT_RECORDED: 'SUPPLIER_PAYMENT_RECORDED',

  // Purchase orders
  PO_CREATED: 'PO_CREATED',
  PO_APPROVED: 'PO_APPROVED',
  PO_RECEIVED: 'PO_RECEIVED',
  PO_CANCELLED: 'PO_CANCELLED',

  // Billing & payments
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  PAYMENT_REVERSED: 'PAYMENT_REVERSED',
  RETURN_CREATED: 'RETURN_CREATED',

  // Expenses
  EXPENSE_CREATED: 'EXPENSE_CREATED',
  EXPENSE_UPDATED: 'EXPENSE_UPDATED',
  EXPENSE_DELETED: 'EXPENSE_DELETED',
  EXPENSE_CATEGORY_CREATED: 'EXPENSE_CATEGORY_CREATED',

  // Restaurant
  TABLE_CREATED: 'TABLE_CREATED',
  TABLE_STATUS_UPDATED: 'TABLE_STATUS_UPDATED',
  TABLE_DELETED: 'TABLE_DELETED',
  KOT_CREATED: 'KOT_CREATED',
  KOT_STATUS_UPDATED: 'KOT_STATUS_UPDATED',
  RECIPE_CREATED: 'RECIPE_CREATED',
  RECIPE_UPDATED: 'RECIPE_UPDATED',
  RECIPE_DELETED: 'RECIPE_DELETED',
  RESTAURANT_DAILY_CLOSE: 'RESTAURANT_DAILY_CLOSE',

  // Backup
  BACKUP_CREATED: 'BACKUP_CREATED',
  BACKUP_RESTORED: 'BACKUP_RESTORED',
  BACKUP_DELETED: 'BACKUP_DELETED',

  // Import
  IMPORT_EXECUTED: 'IMPORT_EXECUTED',

  // Tax
  TAX_CREATED: 'TAX_CREATED',
  TAX_UPDATED: 'TAX_UPDATED',
  TAX_DELETED: 'TAX_DELETED',
} as const

export type AuditEvent = typeof AUDIT_EVENTS[keyof typeof AUDIT_EVENTS]
