import { describe, it, expect, vi, afterAll } from 'vitest'
import { writeFileSync, unlinkSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'

// Isolates these tests from the real Aszurex-mark file read (Electron app.isPackaged
// et al. aren't available outside a real Electron process) — this file's own
// output is exercised directly at scratchpad/uat this session, not here.
vi.mock('../../utils/branding', () => ({
  aszurexFooterHtml: vi.fn().mockResolvedValue('Generated by Sarang Business OS Lite | Aszurex | www.aszurex.com'),
  aszurexBrandSuffixHtml: vi.fn().mockResolvedValue('Aszurex | www.aszurex.com')
}))

// Real bug fix 2026-07-15 gave print.service.ts a real DB dependency for the
// first time (fetching number_format/decimal_places/currency_symbol_position
// Settings for locale-aware amount formatting — see that file's own fix
// comment). No real Prisma connection exists in this unit-test environment,
// so this mock returns an empty settings list, which getPrintFormatSettings
// falls back to defaults for (numberFormat 'IN', decimals 2, prefix) —
// matching this test file's existing fixtures/assertions exactly.
vi.mock('../../database/db', () => ({
  getPrisma: () => ({ setting: { findMany: vi.fn().mockResolvedValue([]) } })
}))

import { printService, logoToBase64DataUri } from '../print.service'

// Minimal but realistic invoice/receipt fixtures, matching what
// billingService.getInvoice() actually returns via its Prisma query
// (src/main/services/billing.service.ts:339-358) — items carry BOTH the
// productName snapshot field (a plain scalar on InvoiceItem, always present)
// and a `product` relation object whose select clause only picks `id`/`unit`,
// never `productName`. A template that reads item.product.productName instead
// of item.productName renders a blank product-name cell on every invoice/
// receipt — this was a real, confirmed bug (found via an end-to-end print of
// an actual created invoice, not a unit test) fixed alongside Phase 39.
function makeInvoice() {
  return {
    invoiceNumber: 'INV-2026-000001',
    invoiceDate: '2026-07-03T00:00:00.000Z',
    status: 'ACTIVE',
    customer: { customerName: 'Print Verify Customer', phone: '9876500000', customerCode: 'CUS-00001' },
    items: [
      {
        productName: 'Print Verify Widget', // the real, always-populated snapshot field
        product: { unit: 'PCS' }, // deliberately NO productName here — matches getInvoice()'s actual select
        quantity: 2,
        unitPrice: 250,
        discountAmount: 0,
        taxRate: 18,
        taxAmount: 90,
        lineTotal: 500,
        variantInfo: null
      }
    ],
    subtotal: 500,
    discountAmount: 0,
    taxAmount: 90,
    roundingAmount: 0,
    totalAmount: 590,
    paidAmount: 590,
    balanceAmount: 0,
    paymentStatus: 'PAID',
    notes: null,
    gstType: 'CGST_SGST'
  }
}

const profile = {
  businessName: 'Test Business',
  currencySymbol: '₹',
  taxModel: 'GST'
}

describe('printService.generateInvoiceHtml', () => {
  it('renders the product name from the InvoiceItem snapshot field, not the (unselected) product relation', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).toContain('Print Verify Widget')
    expect(html).not.toContain('<td></td>') // the exact regression symptom: a blank product-name cell
  })

  it('still renders the unit from the product relation alongside the snapshot name', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).toContain('PCS')
  })
})

// Phase 63 — the editable invoice template system. A thin visual layer:
// financial data must stay byte-identical regardless of template, only
// accent color/footer/density vary.
describe('printService.generateInvoiceHtml — Phase 63 template config', () => {
  it('renders the default accent color and footer text when no template config is given', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).toContain('#00AEEF')
    expect(html).toContain('Thank you for your business!')
    expect(html).toContain('padding: 20mm')
  })

  it('applies a custom accent color throughout, replacing the default everywhere it appears', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { accentColor: '#7C3AED' })
    expect(html).toContain('#7C3AED')
    expect(html).not.toContain('#00AEEF')
  })

  it('applies a custom footer line in place of the default', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { footerText: 'GST Invoice — thank you!' })
    expect(html).toContain('GST Invoice — thank you!')
    expect(html).not.toContain('<p>Thank you for your business!</p>')
  })

  it('compact density reduces body padding without changing any financial figure', async () => {
    const comfortable = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    const compact = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { density: 'compact' })
    expect(compact).toContain('padding: 14mm')
    // Strip the <style> block (the only place padding/color differ) and
    // confirm the remaining document body — every dollar figure, every line
    // item — is byte-identical between the two.
    const stripStyle = (h: string) => h.replace(/<style>[\s\S]*?<\/style>/, '')
    expect(stripStyle(compact)).toBe(stripStyle(comfortable))
  })
})

// 2026-09-03 — real gap found via a side-by-side comparison against an
// actual Zoho Books tax invoice: HSN/SAC, Due Date, Place of Supply and
// Ship To all already existed as real, populated fields on Invoice/
// InvoiceItem (fetched by getInvoice()'s Prisma query) but were never
// rendered anywhere on the printed document. These print unconditionally
// whenever their data is present — matching this file's existing
// convention for legally-relevant fields (e.g. CGST/SGST) — no template
// toggle needed.
describe('printService.generateInvoiceHtml — HSN, Due Date, Place of Supply, Ship To', () => {
  function makeInvoiceWithNewFields() {
    return {
      ...makeInvoice(),
      dueDate: '2026-07-10T00:00:00.000Z',
      buyerState: 'Karnataka (29)',
      deliveryAddress: '99 Warehouse Road, Shivamogga',
      items: [{ ...makeInvoice().items[0], hsnCode: '85287215' }],
    }
  }

  it('shows the HSN/SAC column and code under a GST tax model', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoiceWithNewFields() as never, profile as never)
    expect(html).toContain('HSN/SAC')
    expect(html).toContain('85287215')
  })

  it('omits the HSN/SAC column entirely under a non-GST tax model', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoiceWithNewFields() as never, { ...profile, taxModel: 'VAT' } as never)
    expect(html).not.toContain('HSN/SAC')
    expect(html).not.toContain('85287215')
  })

  it('prints the due date when set', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoiceWithNewFields() as never, profile as never)
    expect(html).toContain('Due:')
  })

  it('omits the due date line entirely when unset', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).not.toContain('Due:')
  })

  it('prints Place of Supply when the invoice has a buyerState', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoiceWithNewFields() as never, profile as never)
    expect(html).toContain('Place of Supply')
    expect(html).toContain('Karnataka (29)')
  })

  it('prints a Ship To section alongside Bill To when deliveryAddress is set', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoiceWithNewFields() as never, profile as never)
    expect(html).toContain('Ship To')
    expect(html).toContain('99 Warehouse Road, Shivamogga')
  })

  it('omits Ship To entirely when deliveryAddress is unset', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).not.toContain('Ship To')
  })
})

describe('printService.generateInvoiceHtml — Amount in Words, Bank Details, Signature Block', () => {
  const bankProfile = { ...profile, bankAccountName: 'Test Business', bankAccountNumber: '1234567890', bankName: 'Test Bank', bankBranch: 'Main Branch', bankIfscCode: 'TEST0001234' }

  it('omits Amount in Words, Bank Details and Signature Block by default (no template config)', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, bankProfile as never)
    expect(html).not.toContain('Amount in Words')
    expect(html).not.toContain('Bank Details')
    expect(html).not.toContain('Authorized Signature')
  })

  it('renders Amount in Words spelled out correctly when the toggle is on', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { showAmountInWords: true })
    expect(html).toContain('Amount in Words')
    // totalAmount 590, INR default -> "Five Hundred Ninety Indian Rupees Only"
    expect(html).toContain('Five Hundred Ninety Indian Rupees Only')
  })

  it('renders Bank Details when the toggle is on and the business has bank fields set', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, bankProfile as never, { showBankDetails: true })
    expect(html).toContain('Bank Details')
    expect(html).toContain('1234567890')
    expect(html).toContain('TEST0001234')
  })

  it('omits Bank Details when the toggle is on but the business has no bank fields set', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { showBankDetails: true })
    expect(html).not.toContain('Bank Details')
  })

  it('renders a signature block with the business name when the toggle is on', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never, { showSignatureBlock: true })
    expect(html).toContain('Authorized Signature')
    expect(html).toContain('For Test Business')
  })
})

// Regression coverage for a real gap found and fixed 2026-07-08: the UPI QR
// only ever checked whether `upiId` was filled in, never the business's
// actual country — UPI is exclusively an Indian payment system, so a
// non-Indian business (or stale/garbage data left in that field) must never
// show a QR that makes no sense to its customers. Zero coverage existed for
// this feature before this pass.
describe('printService UPI QR country gating', () => {
  function makeUnpaidInvoice() {
    return { ...makeInvoice(), balanceAmount: 590, paymentStatus: 'PENDING' }
  }

  it('shows the UPI QR for an Indian business with a real upiId and an outstanding balance', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'IN' } as never)
    expect(html).toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR for a non-Indian business, even with upiId filled in', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'stale@upi', country: 'US' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })

  // Regression for a real gap found 2026-07-13: SetupWizard.tsx's country
  // field is free text defaulting to "India" (never normalized to the ISO
  // code 'IN' anywhere), so a strict `country === 'IN'` check silently
  // disabled the QR for every real Indian setup that used the default value.
  it('shows the UPI QR for the real-world "India" free-text default, not just the ISO code', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'India' } as never)
    expect(html).toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR when upiId is not configured, even for an Indian business', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, country: 'IN' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR once the invoice is fully paid, regardless of country/upiId', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'IN' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })
})

describe('printService.generateReceiptHtml', () => {
  it('renders the product name from the InvoiceItem snapshot field', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, profile as never, '80mm')
    expect(html).toContain('Print Verify Widget')
  })
})

// Phase 44: logo + watermark support
const TEST_LOGO_PATH = join(tmpdir(), 'sarang-print-service-test-logo.png')
// Minimal valid 1x1 transparent PNG — enough for readFileSync + base64 to round-trip.
const ONE_PX_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='
writeFileSync(TEST_LOGO_PATH, Buffer.from(ONE_PX_PNG_BASE64, 'base64'))
afterAll(() => { try { unlinkSync(TEST_LOGO_PATH) } catch { /* best-effort cleanup */ } })

// Module-scoped (not just describe-block-scoped) so every describe block below,
// including the Phase 45 Credit/Debit Note ones, can share these.
const profileWithWatermark = { ...profile, logoPath: TEST_LOGO_PATH, enableDocumentWatermark: true }
const profileWithoutWatermark = { ...profile, logoPath: TEST_LOGO_PATH, enableDocumentWatermark: false }

describe('logoToBase64DataUri', () => {
  it('returns a data: URI with the correct mime type and the file contents base64-encoded', () => {
    const uri = logoToBase64DataUri(TEST_LOGO_PATH)
    expect(uri).toBe(`data:image/png;base64,${ONE_PX_PNG_BASE64}`)
  })
})

describe('printService watermark rendering', () => {

  it('generateInvoiceHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('generateInvoiceHtml omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })

  it('generateReceiptHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, profileWithWatermark as never, '80mm')
    expect(html).toContain('opacity:0.08')
  })

  it('generateQuotationHtml renders the logo image when logoPath is set', async () => {
    const quotation = {
      quotationNumber: 'QT-2026-000001',
      customerName: 'Print Verify Customer',
      items: [{ productName: 'Print Verify Widget', quantity: 1, unitPrice: 100, discount: 0, taxRate: 0, lineTotal: 100 }],
      subtotal: 100, discountAmount: 0, taxAmount: 0, totalAmount: 100, notes: null
    }
    const html = await printService.generateQuotationHtml(quotation as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('generateQuotationHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const quotation = {
      quotationNumber: 'QT-2026-000001',
      customerName: 'Print Verify Customer',
      items: [{ productName: 'Print Verify Widget', quantity: 1, unitPrice: 100, discount: 0, taxRate: 0, lineTotal: 100 }],
      subtotal: 100, discountAmount: 0, taxAmount: 0, totalAmount: 100, notes: null
    }
    const html = await printService.generateQuotationHtml(quotation as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })
})

// Phase 45: Credit Note / Debit Note — flat summary documents (no line items,
// no tax breakdown — confirmed out of scope at Phase 45's own audit).
describe('printService.generateCreditNoteHtml', () => {
  const creditNote = {
    creditNoteNumber: 'CN-00001',
    createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Return of damaged item',
    amount: 250,
    notes: null,
    customer: { customerName: 'Print Verify Customer', phone: '9876500000' },
    invoice: null
  }

  it('renders the reason and amount', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profile as never)
    expect(html).toContain('Return of damaged item')
    expect(html).toContain('250.00')
  })

  it('omits the invoice reference line when no invoice is linked', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profile as never)
    expect(html).not.toContain('Against Invoice')
  })

  it('renders the invoice reference line when an invoice is linked', async () => {
    const withInvoice = { ...creditNote, invoice: { invoiceNumber: 'INV-2026-000001', invoiceDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateCreditNoteHtml(withInvoice as never, profile as never)
    expect(html).toContain('Against Invoice')
    expect(html).toContain('INV-2026-000001')
  })

  it('renders the logo when logoPath is set', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })
})

describe('printService.generateDebitNoteHtml', () => {
  const debitNote = {
    debitNoteNumber: 'DN-00001',
    createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Quality issue on delivery',
    amount: 400,
    notes: null,
    supplier: { supplierName: 'Print Verify Supplier', phone: '9876500001' },
    purchaseOrder: null
  }

  it('renders the reason and amount', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profile as never)
    expect(html).toContain('Quality issue on delivery')
    expect(html).toContain('400.00')
  })

  it('omits the purchase order reference line when no PO is linked', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profile as never)
    expect(html).not.toContain('Against Purchase Order')
  })

  it('renders the purchase order reference line when a PO is linked', async () => {
    const withPO = { ...debitNote, purchaseOrder: { poNumber: 'PO-00001', orderDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateDebitNoteHtml(withPO as never, profile as never)
    expect(html).toContain('Against Purchase Order')
    expect(html).toContain('PO-00001')
  })

  it('renders the logo when logoPath is set', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })
})

// Fresh-audit fix (2026-07-12): thermal receipt-width variants for
// Quotation/Credit Note/Debit Note — previously only Invoice had a thermal
// template at all, so these had no path onto a shop's thermal printer.
describe('printService thermal receipt variants (Quotation / Credit Note / Debit Note)', () => {
  const quotation = {
    quotationNumber: 'QT-2026-000001',
    customerName: 'Print Verify Customer',
    validUntil: '2026-08-01T00:00:00.000Z',
    items: [{ productName: 'Print Verify Widget', quantity: 2, unitPrice: 100, discount: 0, taxRate: 18, lineTotal: 236 }],
    subtotal: 200, discountAmount: 0, taxAmount: 36, totalAmount: 236, notes: null
  }
  const creditNote = {
    creditNoteNumber: 'CN-00001', createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Return of damaged item', amount: 250, notes: null,
    customer: { customerName: 'Print Verify Customer', phone: '9876500000' }, invoice: null
  }
  const debitNote = {
    debitNoteNumber: 'DN-00001', createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Quality issue on delivery', amount: 400, notes: null,
    supplier: { supplierName: 'Print Verify Supplier', phone: '9876500001' }, purchaseOrder: null
  }

  it('generateQuotationReceiptHtml renders items and total at 80mm width', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '80mm')
    expect(html).toContain('width: 72mm')
    expect(html).toContain('Print Verify Widget')
    expect(html).toContain('QUOTATION: QT-2026-000001')
    expect(html).toContain('236.00')
  })

  it('generateQuotationReceiptHtml narrows to 56mm and tightens font at 58mm width', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '58mm')
    expect(html).toContain('width: 56mm')
    expect(html).toContain('font-size: 9px')
  })

  it('generateQuotationReceiptHtml includes Aszurex branding', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '80mm')
    expect(html).toContain('Aszurex')
  })

  it('generateCreditNoteReceiptHtml renders the reason and amount at 80mm width', async () => {
    const html = await printService.generateCreditNoteReceiptHtml(creditNote as never, profile as never, '80mm')
    expect(html).toContain('width: 72mm')
    expect(html).toContain('Return of damaged item')
    expect(html).toContain('CREDIT NOTE: CN-00001')
    expect(html).toContain('250.00')
    expect(html).toContain('Aszurex')
  })

  it('generateCreditNoteReceiptHtml renders the invoice reference line when linked', async () => {
    const withInvoice = { ...creditNote, invoice: { invoiceNumber: 'INV-2026-000001', invoiceDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateCreditNoteReceiptHtml(withInvoice as never, profile as never, '80mm')
    expect(html).toContain('Against Invoice')
    expect(html).toContain('INV-2026-000001')
  })

  it('generateDebitNoteReceiptHtml renders the reason and amount at 58mm width', async () => {
    const html = await printService.generateDebitNoteReceiptHtml(debitNote as never, profile as never, '58mm')
    expect(html).toContain('width: 56mm')
    expect(html).toContain('Quality issue on delivery')
    expect(html).toContain('DEBIT NOTE: DN-00001')
    expect(html).toContain('400.00')
    expect(html).toContain('Aszurex')
  })

  it('generateDebitNoteReceiptHtml renders the purchase order reference line when linked', async () => {
    const withPO = { ...debitNote, purchaseOrder: { poNumber: 'PO-00001', orderDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateDebitNoteReceiptHtml(withPO as never, profile as never, '80mm')
    // Abbreviated to "Against PO" (not the A4 template's "Against Purchase
    // Order") — a deliberate space-saving choice for narrow receipt paper.
    expect(html).toContain('Against PO')
    expect(html).toContain('PO-00001')
  })
})

// Phase 52 audit: generateLabelHtml previously carried only plain
// "Sarang · Aszurex" text — no partnership mark, no website — the one print
// surface that fell short of every other template's branding. Now async,
// reusing aszurexBrandSuffixHtml like the other 6 templates.
describe('printService.generateLabelHtml', () => {
  const params = {
    labels: [{ productName: 'Amul Butter 500g', barcode: '1234567890123', priceText: 'Rs 285.00', copies: 1 }],
    outputMode: 'THERMAL_LABEL' as const,
    labelSizeMm: { width: 40, height: 30 },
    fields: { showPrice: true, showBarcode: true, showName: true },
    businessName: 'Test Store',
  }

  it('includes the real Aszurex brand suffix (mark + website), not just plain text', async () => {
    const html = await printService.generateLabelHtml(params)
    expect(html).toContain('Sarang · Aszurex | www.aszurex.com')
  })

  it('still renders the product name, price, and barcode', async () => {
    const html = await printService.generateLabelHtml(params)
    expect(html).toContain('Amul Butter 500g')
    expect(html).toContain('Rs 285.00')
    expect(html).toContain('1234567890123')
  })
})

// Regression for a real defect found 2026-07-22: a RETURN-type invoice
// (status: 'ACTIVE', totalAmount negative per returns.service.ts) printed
// through this exact template with no visual distinction from a normal
// sale — a green "ACTIVE" badge, a positive-looking total (Math.abs'd), and
// no "RETURN"/"REFUND" wording anywhere. The only signal was the "RET-"
// prefix in the invoice number.
describe('printService — RETURN invoice visual distinction', () => {
  it('generateInvoiceHtml shows a RETURN banner and badge, not a misleading green ACTIVE badge', async () => {
    const html = await printService.generateInvoiceHtml({ ...makeInvoice(), invoiceType: 'RETURN', invoiceNumber: 'RET-2026-000001' } as never, profile as never)

    expect(html).toContain('RETURN / REFUND')
    expect(html).toContain('status-RETURN')
    expect(html).not.toMatch(/status-badge status-ACTIVE/)
  })

  it('generateInvoiceHtml still shows the normal green ACTIVE badge for a real (non-return) sale', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)

    expect(html).toContain('status-badge status-ACTIVE')
    expect(html).not.toContain('RETURN / REFUND')
  })

  it('generateReceiptHtml shows a RETURN marker for a return invoice', async () => {
    const html = await printService.generateReceiptHtml({ ...makeInvoice(), invoiceType: 'RETURN', invoiceNumber: 'RET-2026-000001' } as never, profile as never, '80mm')

    expect(html).toContain('RETURN / REFUND')
  })

  it('generateReceiptHtml shows no RETURN marker for a real (non-return) sale', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, profile as never, '80mm')

    expect(html).not.toContain('RETURN / REFUND')
  })
})

// Phase 62 — Composition Scheme dealers are legally barred from issuing a
// tax invoice; the document itself must be relabelled "Bill of Supply".
describe('printService — Composition Scheme "Bill of Supply" labelling', () => {
  it('generateInvoiceHtml labels the document "Bill of Supply" when the business is on the Composition Scheme', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, { ...profile, gstScheme: 'COMPOSITION' } as never)

    expect(html).toContain('Bill of Supply')
    expect(html).not.toMatch(/<title>Invoice /)
    expect(html).not.toMatch(/inv-number">Invoice /)
  })

  it('generateInvoiceHtml still says "Invoice" for a REGULAR-scheme business', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, { ...profile, gstScheme: 'REGULAR' } as never)

    expect(html).not.toContain('Bill of Supply')
    expect(html).toMatch(/inv-number">Invoice /)
  })

  it('generateInvoiceHtml keeps the "Return" label on a RETURN document even under Composition Scheme, never "Bill of Supply"', async () => {
    const html = await printService.generateInvoiceHtml({ ...makeInvoice(), invoiceType: 'RETURN', invoiceNumber: 'RET-2026-000001' } as never, { ...profile, gstScheme: 'COMPOSITION' } as never)

    expect(html).not.toContain('Bill of Supply')
    expect(html).toMatch(/inv-number">Return /)
  })

  it('generateReceiptHtml labels the document "Bill of Supply" when the business is on the Composition Scheme', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, { ...profile, gstScheme: 'COMPOSITION' } as never, '80mm')

    expect(html).toContain('Bill of Supply')
  })
})

// Real print gap closed 2026-08-12 (user-reported: "ensure we can print all
// kinds of invoices and bill") — Bill had zero print/PDF support at all
// before this. Mirrors generatePurchaseOrderHtml's own test coverage shape.
describe('printService.generateBillHtml', () => {
  const bill = {
    billNumber: 'BILL-00001',
    billDate: '2026-08-01T00:00:00.000Z',
    dueDate: '2026-08-15T00:00:00.000Z',
    status: 'OPEN',
    notes: null,
    supplier: { supplierName: 'Print Verify Supplier', supplierCode: 'SUP-00001', phone: '9876500000' },
    items: [
      { quantity: 3, unitCost: 100, taxRate: 18, total: 354, product: { productName: 'Print Verify Widget', sku: 'PVW-01', unit: 'PCS' }, serviceDescription: null }
    ],
    subtotal: 300, taxAmount: 54, totalAmount: 354, balanceAmount: 354
  }

  it('renders the bill number, supplier, and a product line', async () => {
    const html = await printService.generateBillHtml(bill as never, profile as never)
    expect(html).toContain('BILL-00001')
    expect(html).toContain('Print Verify Supplier')
    expect(html).toContain('Print Verify Widget')
    expect(html).toContain('354.00')
  })

  it('renders a service-only line via serviceDescription when product is null', async () => {
    const serviceBill = { ...bill, items: [{ quantity: 1, unitCost: 5000, taxRate: 18, total: 5900, product: null, serviceDescription: 'Consulting fee' }] }
    const html = await printService.generateBillHtml(serviceBill as never, profile as never)
    expect(html).toContain('Consulting fee')
  })

  it('shows Balance Due only when it differs from the total (partially paid)', async () => {
    const partiallyPaid = { ...bill, balanceAmount: 100 }
    const html = await printService.generateBillHtml(partiallyPaid as never, profile as never)
    expect(html).toContain('Balance Due')
    const fullyOwed = { ...bill, balanceAmount: bill.totalAmount }
    const htmlFull = await printService.generateBillHtml(fullyOwed as never, profile as never)
    expect(htmlFull).not.toContain('Balance Due')
  })
})

describe('printService.generateSalesOrderHtml', () => {
  const salesOrder = {
    soNumber: 'SO-00001',
    orderDate: '2026-08-01T00:00:00.000Z',
    expectedDate: '2026-08-10T00:00:00.000Z',
    status: 'CONFIRMED',
    notes: null,
    customer: { customerName: 'Print Verify Customer', customerCode: 'CUS-00001', phone: '9876500000' },
    items: [
      { quantity: 5, unitPrice: 100, taxRate: 0, total: 500, product: { productName: 'Print Verify Widget', sku: 'PVW-01', unit: 'PCS' }, serviceDescription: null }
    ],
    subtotal: 500, taxAmount: 0, totalAmount: 500
  }

  it('renders the SO number, customer, and a product line', async () => {
    const html = await printService.generateSalesOrderHtml(salesOrder as never, profile as never)
    expect(html).toContain('SO-00001')
    expect(html).toContain('Print Verify Customer')
    expect(html).toContain('Print Verify Widget')
    expect(html).toContain('500.00')
  })

  it('renders a service-only line via serviceDescription when product is null', async () => {
    const serviceSO = { ...salesOrder, items: [{ quantity: 1, unitPrice: 2000, taxRate: 18, total: 2360, product: null, serviceDescription: 'Consulting fee' }] }
    const html = await printService.generateSalesOrderHtml(serviceSO as never, profile as never)
    expect(html).toContain('Consulting fee')
  })

  it('shows the status badge with underscores replaced by spaces', async () => {
    const pending = { ...salesOrder, status: 'PENDING_APPROVAL' }
    const html = await printService.generateSalesOrderHtml(pending as never, profile as never)
    expect(html).toContain('PENDING APPROVAL')
  })
})

// Real gap found+fixed 2026-08-12 (post-phase completeness audit): the
// spec explicitly requires drop-shipment to change the PO's own printed
// delivery address — `dropShipToCustomer` was captured/stored since
// Task #3's own build but the print template never actually read it.
describe('printService.generatePurchaseOrderHtml — drop-shipment', () => {
  const po = {
    poNumber: 'PO-00001',
    orderDate: '2026-08-01T00:00:00.000Z',
    status: 'DRAFT',
    notes: null,
    supplier: { supplierName: 'Print Verify Supplier', supplierCode: 'SUP-00001', phone: '9876500000' },
    items: [
      { quantity: 5, unitCost: 100, taxRate: 0, total: 500, product: { productName: 'Print Verify Widget', sku: 'PVW-01', unit: 'PCS' } }
    ],
    subtotal: 500, taxAmount: 0, totalAmount: 500
  }

  it('renders a Ship To section with the drop-ship customer when set', async () => {
    const withDropShip = { ...po, dropShipToCustomer: { customerName: 'Print Verify Drop-Ship Customer', address: '123 Test Lane', city: 'Mumbai', state: 'Maharashtra', phone: '9123456789' } }
    const html = await printService.generatePurchaseOrderHtml(withDropShip as never, profile as never)
    expect(html).toContain('Ship To (Drop-Ship)')
    expect(html).toContain('Print Verify Drop-Ship Customer')
    expect(html).toContain('123 Test Lane')
    expect(html).toContain('Mumbai')
  })

  it('omits the Ship To section entirely when no drop-ship customer is set', async () => {
    const html = await printService.generatePurchaseOrderHtml(po as never, profile as never)
    expect(html).not.toContain('Ship To (Drop-Ship)')
  })
})
