import { describe, it, expect, vi, afterAll } from 'vitest'
import { writeFileSync, unlinkSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'

// Isolates these tests from the real Aszurex-mark file read (Electron app.isPackaged
// et al. aren't available outside a real Electron process) — this file's own
// output is exercised directly at scratchpad/uat this session, not here.
vi.mock('../../utils/branding', () => ({
  aszurexFooterHtml: vi.fn().mockResolvedValue('Generated by Sarang Business OS Lite | Aszurex | www.aszurex.com'),
  aszurexBrandSuffixHtml: vi.fn().mockResolvedValue('Aszurex | www.aszurex.com')
}))

import { printService, logoToBase64DataUri } from '../print.service'

// Minimal but realistic invoice/receipt fixtures, matching what
// billingService.getInvoice() actually returns via its Prisma query
// (src/main/services/billing.service.ts:339-358) — items carry BOTH the
// productName snapshot field (a plain scalar on InvoiceItem, always present)
// and a `product` relation object whose select clause only picks `id`/`unit`,
// never `productName`. A template that reads item.product.productName instead
// of item.productName renders a blank product-name cell on every invoice/
// receipt — this was a real, confirmed bug (found via an end-to-end print of
// an actual created invoice, not a unit test) fixed alongside Phase 39.
function makeInvoice() {
  return {
    invoiceNumber: 'INV-2026-000001',
    invoiceDate: '2026-07-03T00:00:00.000Z',
    status: 'ACTIVE',
    customer: { customerName: 'Print Verify Customer', phone: '9876500000', customerCode: 'CUS-00001' },
    items: [
      {
        productName: 'Print Verify Widget', // the real, always-populated snapshot field
        product: { unit: 'PCS' }, // deliberately NO productName here — matches getInvoice()'s actual select
        quantity: 2,
        unitPrice: 250,
        discountAmount: 0,
        taxRate: 18,
        taxAmount: 90,
        lineTotal: 500,
        variantInfo: null
      }
    ],
    subtotal: 500,
    discountAmount: 0,
    taxAmount: 90,
    roundingAmount: 0,
    totalAmount: 590,
    paidAmount: 590,
    balanceAmount: 0,
    paymentStatus: 'PAID',
    notes: null,
    gstType: 'CGST_SGST'
  }
}

const profile = {
  businessName: 'Test Business',
  currencySymbol: '₹',
  taxModel: 'GST'
}

describe('printService.generateInvoiceHtml', () => {
  it('renders the product name from the InvoiceItem snapshot field, not the (unselected) product relation', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).toContain('Print Verify Widget')
    expect(html).not.toContain('<td></td>') // the exact regression symptom: a blank product-name cell
  })

  it('still renders the unit from the product relation alongside the snapshot name', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profile as never)
    expect(html).toContain('PCS')
  })
})

// Regression coverage for a real gap found and fixed 2026-07-08: the UPI QR
// only ever checked whether `upiId` was filled in, never the business's
// actual country — UPI is exclusively an Indian payment system, so a
// non-Indian business (or stale/garbage data left in that field) must never
// show a QR that makes no sense to its customers. Zero coverage existed for
// this feature before this pass.
describe('printService UPI QR country gating', () => {
  function makeUnpaidInvoice() {
    return { ...makeInvoice(), balanceAmount: 590, paymentStatus: 'PENDING' }
  }

  it('shows the UPI QR for an Indian business with a real upiId and an outstanding balance', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'IN' } as never)
    expect(html).toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR for a non-Indian business, even with upiId filled in', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'stale@upi', country: 'US' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })

  // Regression for a real gap found 2026-07-13: SetupWizard.tsx's country
  // field is free text defaulting to "India" (never normalized to the ISO
  // code 'IN' anywhere), so a strict `country === 'IN'` check silently
  // disabled the QR for every real Indian setup that used the default value.
  it('shows the UPI QR for the real-world "India" free-text default, not just the ISO code', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'India' } as never)
    expect(html).toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR when upiId is not configured, even for an Indian business', async () => {
    const html = await printService.generateInvoiceHtml(makeUnpaidInvoice() as never, { ...profile, country: 'IN' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })

  it('never shows the UPI QR once the invoice is fully paid, regardless of country/upiId', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, { ...profile, upiId: 'biz@upi', country: 'IN' } as never)
    expect(html).not.toContain('Scan to Pay (UPI)')
  })
})

describe('printService.generateReceiptHtml', () => {
  it('renders the product name from the InvoiceItem snapshot field', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, profile as never, '80mm')
    expect(html).toContain('Print Verify Widget')
  })
})

// Phase 44: logo + watermark support
const TEST_LOGO_PATH = join(tmpdir(), 'sarang-print-service-test-logo.png')
// Minimal valid 1x1 transparent PNG — enough for readFileSync + base64 to round-trip.
const ONE_PX_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='
writeFileSync(TEST_LOGO_PATH, Buffer.from(ONE_PX_PNG_BASE64, 'base64'))
afterAll(() => { try { unlinkSync(TEST_LOGO_PATH) } catch { /* best-effort cleanup */ } })

// Module-scoped (not just describe-block-scoped) so every describe block below,
// including the Phase 45 Credit/Debit Note ones, can share these.
const profileWithWatermark = { ...profile, logoPath: TEST_LOGO_PATH, enableDocumentWatermark: true }
const profileWithoutWatermark = { ...profile, logoPath: TEST_LOGO_PATH, enableDocumentWatermark: false }

describe('logoToBase64DataUri', () => {
  it('returns a data: URI with the correct mime type and the file contents base64-encoded', () => {
    const uri = logoToBase64DataUri(TEST_LOGO_PATH)
    expect(uri).toBe(`data:image/png;base64,${ONE_PX_PNG_BASE64}`)
  })
})

describe('printService watermark rendering', () => {

  it('generateInvoiceHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('generateInvoiceHtml omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateInvoiceHtml(makeInvoice() as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })

  it('generateReceiptHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateReceiptHtml(makeInvoice() as never, profileWithWatermark as never, '80mm')
    expect(html).toContain('opacity:0.08')
  })

  it('generateQuotationHtml renders the logo image when logoPath is set', async () => {
    const quotation = {
      quotationNumber: 'QT-2026-000001',
      customerName: 'Print Verify Customer',
      items: [{ productName: 'Print Verify Widget', quantity: 1, unitPrice: 100, discount: 0, taxRate: 0, lineTotal: 100 }],
      subtotal: 100, discountAmount: 0, taxAmount: 0, totalAmount: 100, notes: null
    }
    const html = await printService.generateQuotationHtml(quotation as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('generateQuotationHtml includes a watermark image when enableDocumentWatermark is true', async () => {
    const quotation = {
      quotationNumber: 'QT-2026-000001',
      customerName: 'Print Verify Customer',
      items: [{ productName: 'Print Verify Widget', quantity: 1, unitPrice: 100, discount: 0, taxRate: 0, lineTotal: 100 }],
      subtotal: 100, discountAmount: 0, taxAmount: 0, totalAmount: 100, notes: null
    }
    const html = await printService.generateQuotationHtml(quotation as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })
})

// Phase 45: Credit Note / Debit Note — flat summary documents (no line items,
// no tax breakdown — confirmed out of scope at Phase 45's own audit).
describe('printService.generateCreditNoteHtml', () => {
  const creditNote = {
    creditNoteNumber: 'CN-00001',
    createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Return of damaged item',
    amount: 250,
    notes: null,
    customer: { customerName: 'Print Verify Customer', phone: '9876500000' },
    invoice: null
  }

  it('renders the reason and amount', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profile as never)
    expect(html).toContain('Return of damaged item')
    expect(html).toContain('250.00')
  })

  it('omits the invoice reference line when no invoice is linked', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profile as never)
    expect(html).not.toContain('Against Invoice')
  })

  it('renders the invoice reference line when an invoice is linked', async () => {
    const withInvoice = { ...creditNote, invoice: { invoiceNumber: 'INV-2026-000001', invoiceDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateCreditNoteHtml(withInvoice as never, profile as never)
    expect(html).toContain('Against Invoice')
    expect(html).toContain('INV-2026-000001')
  })

  it('renders the logo when logoPath is set', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateCreditNoteHtml(creditNote as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })
})

describe('printService.generateDebitNoteHtml', () => {
  const debitNote = {
    debitNoteNumber: 'DN-00001',
    createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Quality issue on delivery',
    amount: 400,
    notes: null,
    supplier: { supplierName: 'Print Verify Supplier', phone: '9876500001' },
    purchaseOrder: null
  }

  it('renders the reason and amount', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profile as never)
    expect(html).toContain('Quality issue on delivery')
    expect(html).toContain('400.00')
  })

  it('omits the purchase order reference line when no PO is linked', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profile as never)
    expect(html).not.toContain('Against Purchase Order')
  })

  it('renders the purchase order reference line when a PO is linked', async () => {
    const withPO = { ...debitNote, purchaseOrder: { poNumber: 'PO-00001', orderDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateDebitNoteHtml(withPO as never, profile as never)
    expect(html).toContain('Against Purchase Order')
    expect(html).toContain('PO-00001')
  })

  it('renders the logo when logoPath is set', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, { ...profile, logoPath: TEST_LOGO_PATH } as never)
    expect(html).toContain('<img src="file:///')
  })

  it('includes a watermark image when enableDocumentWatermark is true', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profileWithWatermark as never)
    expect(html).toContain('opacity:0.08')
  })

  it('omits the watermark when enableDocumentWatermark is false', async () => {
    const html = await printService.generateDebitNoteHtml(debitNote as never, profileWithoutWatermark as never)
    expect(html).not.toContain('opacity:0.08')
  })
})

// Fresh-audit fix (2026-07-12): thermal receipt-width variants for
// Quotation/Credit Note/Debit Note — previously only Invoice had a thermal
// template at all, so these had no path onto a shop's thermal printer.
describe('printService thermal receipt variants (Quotation / Credit Note / Debit Note)', () => {
  const quotation = {
    quotationNumber: 'QT-2026-000001',
    customerName: 'Print Verify Customer',
    validUntil: '2026-08-01T00:00:00.000Z',
    items: [{ productName: 'Print Verify Widget', quantity: 2, unitPrice: 100, discount: 0, taxRate: 18, lineTotal: 236 }],
    subtotal: 200, discountAmount: 0, taxAmount: 36, totalAmount: 236, notes: null
  }
  const creditNote = {
    creditNoteNumber: 'CN-00001', createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Return of damaged item', amount: 250, notes: null,
    customer: { customerName: 'Print Verify Customer', phone: '9876500000' }, invoice: null
  }
  const debitNote = {
    debitNoteNumber: 'DN-00001', createdAt: '2026-07-07T00:00:00.000Z',
    reason: 'Quality issue on delivery', amount: 400, notes: null,
    supplier: { supplierName: 'Print Verify Supplier', phone: '9876500001' }, purchaseOrder: null
  }

  it('generateQuotationReceiptHtml renders items and total at 80mm width', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '80mm')
    expect(html).toContain('width: 72mm')
    expect(html).toContain('Print Verify Widget')
    expect(html).toContain('QUOTATION: QT-2026-000001')
    expect(html).toContain('236.00')
  })

  it('generateQuotationReceiptHtml narrows to 56mm and tightens font at 58mm width', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '58mm')
    expect(html).toContain('width: 56mm')
    expect(html).toContain('font-size: 9px')
  })

  it('generateQuotationReceiptHtml includes Aszurex branding', async () => {
    const html = await printService.generateQuotationReceiptHtml(quotation as never, profile as never, '80mm')
    expect(html).toContain('Aszurex')
  })

  it('generateCreditNoteReceiptHtml renders the reason and amount at 80mm width', async () => {
    const html = await printService.generateCreditNoteReceiptHtml(creditNote as never, profile as never, '80mm')
    expect(html).toContain('width: 72mm')
    expect(html).toContain('Return of damaged item')
    expect(html).toContain('CREDIT NOTE: CN-00001')
    expect(html).toContain('250.00')
    expect(html).toContain('Aszurex')
  })

  it('generateCreditNoteReceiptHtml renders the invoice reference line when linked', async () => {
    const withInvoice = { ...creditNote, invoice: { invoiceNumber: 'INV-2026-000001', invoiceDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateCreditNoteReceiptHtml(withInvoice as never, profile as never, '80mm')
    expect(html).toContain('Against Invoice')
    expect(html).toContain('INV-2026-000001')
  })

  it('generateDebitNoteReceiptHtml renders the reason and amount at 58mm width', async () => {
    const html = await printService.generateDebitNoteReceiptHtml(debitNote as never, profile as never, '58mm')
    expect(html).toContain('width: 56mm')
    expect(html).toContain('Quality issue on delivery')
    expect(html).toContain('DEBIT NOTE: DN-00001')
    expect(html).toContain('400.00')
    expect(html).toContain('Aszurex')
  })

  it('generateDebitNoteReceiptHtml renders the purchase order reference line when linked', async () => {
    const withPO = { ...debitNote, purchaseOrder: { poNumber: 'PO-00001', orderDate: '2026-07-01T00:00:00.000Z' } }
    const html = await printService.generateDebitNoteReceiptHtml(withPO as never, profile as never, '80mm')
    // Abbreviated to "Against PO" (not the A4 template's "Against Purchase
    // Order") — a deliberate space-saving choice for narrow receipt paper.
    expect(html).toContain('Against PO')
    expect(html).toContain('PO-00001')
  })
})

// Phase 52 audit: generateLabelHtml previously carried only plain
// "Sarang · Aszurex" text — no partnership mark, no website — the one print
// surface that fell short of every other template's branding. Now async,
// reusing aszurexBrandSuffixHtml like the other 6 templates.
describe('printService.generateLabelHtml', () => {
  const params = {
    labels: [{ productName: 'Amul Butter 500g', barcode: '1234567890123', priceText: 'Rs 285.00', copies: 1 }],
    outputMode: 'THERMAL_LABEL' as const,
    labelSizeMm: { width: 40, height: 30 },
    fields: { showPrice: true, showBarcode: true, showName: true },
    businessName: 'Test Store',
  }

  it('includes the real Aszurex brand suffix (mark + website), not just plain text', async () => {
    const html = await printService.generateLabelHtml(params)
    expect(html).toContain('Sarang · Aszurex | www.aszurex.com')
  })

  it('still renders the product name, price, and barcode', async () => {
    const html = await printService.generateLabelHtml(params)
    expect(html).toContain('Amul Butter 500g')
    expect(html).toContain('Rs 285.00')
    expect(html).toContain('1234567890123')
  })
})
