import { partnershipMarkBase64DataUri } from '@renderer/assets/branding/partnership-mark-base64'

/**
 * The standard "Generated by Sarang Business OS Lite | Aszurex [mark] | www.aszurex.com"
 * footer, for the renderer-side screens that build print HTML as a raw string
 * for `window.open('', '_blank')` (a popup document has no resolvable base URL
 * for a relative asset path, so the mark must be a self-contained data URI —
 * see scripts/prepare-brand-assets.js for how partnership-mark-base64.ts is
 * generated). For real JSX print views, use <AszurexMark> from
 * @shared/ui/atoms/Brand directly instead of this string helper.
 */
export function aszurexFooterHtml(fontSizePx = 8): string {
  const mark = `<img src="${partnershipMarkBase64DataUri}" alt="" style="height:${fontSizePx + 4}px;width:auto;vertical-align:middle;margin:0 2px" />`
  return `Generated by Sarang Business OS Lite | Aszurex${mark} | www.aszurex.com`
}
