import { partnershipMarkBase64DataUri } from '@renderer/assets/branding/partnership-mark-base64'

/**
 * The standard "Generated by Sarang Business OS Lite | Aszurex [mark] | www.aszurex.com"
 * footer, for the renderer-side screens that build print HTML as a raw string
 * for `window.open('', '_blank')` (a popup document has no resolvable base URL
 * for a relative asset path, so the mark must be a self-contained data URI —
 * see scripts/prepare-brand-assets.js for how partnership-mark-base64.ts is
 * generated). For real JSX print views, use <AszurexMark> from
 * @shared/ui/atoms/Brand directly instead of this string helper.
 */
export function aszurexFooterHtml(fontSizePx = 8): string {
  const mark = `<img src="${partnershipMarkBase64DataUri}" alt="" style="height:${fontSizePx + 4}px;width:auto;vertical-align:middle;margin:0 2px" />`
  return `Generated by Sarang Business OS Lite | Aszurex${mark} | www.aszurex.com`
}

/**
 * Opens a print-ready popup for any LAN-only QR code (Doctor Pad, Token
 * Queue check-in, Kitchen Display, Field Order, waiting-room display, etc.)
 * — one shared layout so every one of these carries the same "same Wi-Fi
 * only" warning on the printed sheet itself, not just in the desktop panel
 * that generated it (a printout gets handed to/posted for someone who never
 * saw that panel).
 */
export function printLanQrHtml(params: { title: string; subtitle: string; qrDataUrl: string; url?: string; disclaimer: string }): void {
  const w = window.open('', '_blank')
  const html = `<html><head><style>
    body{font-family:Arial,sans-serif;text-align:center;padding:40px}
    h1{font-size:20px;margin-bottom:4px}
    h2{font-size:13px;color:#666;font-weight:600;margin:0 0 16px}
    img{width:220px;height:220px}
    .url{font-size:11px;color:#666;margin-top:10px;word-break:break-all}
    .disclaimer{font-size:11px;color:#B45309;background:#FFFBEB;border:1px solid #FDE68A;border-radius:8px;padding:10px;margin:16px auto 0;max-width:320px}
    footer{margin-top:24px;font-size:10px;color:#888}
  </style></head><body><h1>${params.title}</h1><h2>${params.subtitle}</h2><img src="${params.qrDataUrl}" alt="QR code" />${params.url ? `<p class="url">${params.url}</p>` : ''}<p class="disclaimer">${params.disclaimer}</p><footer>${aszurexFooterHtml(10)}</footer></body></html>`
  if (w) { w.document.write(html); w.document.close(); w.print() }
}
